const mongoose = require('mongoose');

const memberSchema = new mongoose.Schema({
    memberId : String,
    joinerId : String,
    joinerName : String,
    type : String,
    package : String,
    firstName : String,
    middleName : String,
    lastName : String,
    dob : String,
    block : String,
    mohalla : String,
    shopName : String,
    idProof : String,
    addressProof : String,
    shopPhoto : String,
    shopType : String,
    qualification : String,
    population : String,
    locationType : String,
    location : String,
    emailId : String,
    mobile : String,
    landLine : String,
    aepsStatus : String,
    country : String,
    state : String,
    district : String,
    city : String,
    landmark : String,
    pincode : String,
    address : String,
    aadharnumber : String,
    pannumber : String,
    password : String,
    permission : String,
    aadharImage : String,
    pancardImage : String,
    passbookImage : String,
    userPhoto : String,
    formImage : String,
    status : Number,
    narration : String,
    userCode : String,
}, { timestamps: true });

const Member = mongoose.model('Member', memberSchema);
module.exports = Member;
